/*  This header was auto-generated by the UnicodeHPP (Unicode C++ Header Generator)
 *  that is located at git.stabletec.com/utilities/unicode-hpp
 *
 *  Check for an updated version anytime, or state concerns/bugs.
 */


#ifndef UNICODE_BLOCKS_HPP
#define UNICODE_BLOCKS_HPP

#include <cstdint>

namespace unicode {

// The Unicode Version this is based on.
const char* version_str = "13_0_0";

enum class Block : uint32_t {
    Basic_Latin,
    Latin_1_Supplement,
    Latin_Extended_A,
    Latin_Extended_B,
    IPA_Extensions,
    Spacing_Modifier_Letters,
    Combining_Diacritical_Marks,
    Greek_and_Coptic,
    Cyrillic,
    Cyrillic_Supplement,
    Armenian,
    Hebrew,
    Arabic,
    Syriac,
    Arabic_Supplement,
    Thaana,
    NKo,
    Samaritan,
    Mandaic,
    Syriac_Supplement,
    Arabic_Extended_A,
    Devanagari,
    Bengali,
    Gurmukhi,
    Gujarati,
    Oriya,
    Tamil,
    Telugu,
    Kannada,
    Malayalam,
    Sinhala,
    Thai,
    Lao,
    Tibetan,
    Myanmar,
    Georgian,
    Hangul_Jamo,
    Ethiopic,
    Ethiopic_Supplement,
    Cherokee,
    Unified_Canadian_Aboriginal_Syllabics,
    Ogham,
    Runic,
    Tagalog,
    Hanunoo,
    Buhid,
    Tagbanwa,
    Khmer,
    Mongolian,
    Unified_Canadian_Aboriginal_Syllabics_Extended,
    Limbu,
    Tai_Le,
    New_Tai_Lue,
    Khmer_Symbols,
    Buginese,
    Tai_Tham,
    Combining_Diacritical_Marks_Extended,
    Balinese,
    Sundanese,
    Batak,
    Lepcha,
    Ol_Chiki,
    Cyrillic_Extended_C,
    Georgian_Extended,
    Sundanese_Supplement,
    Vedic_Extensions,
    Phonetic_Extensions,
    Phonetic_Extensions_Supplement,
    Combining_Diacritical_Marks_Supplement,
    Latin_Extended_Additional,
    Greek_Extended,
    General_Punctuation,
    Superscripts_and_Subscripts,
    Currency_Symbols,
    Combining_Diacritical_Marks_for_Symbols,
    Letterlike_Symbols,
    Number_Forms,
    Arrows,
    Mathematical_Operators,
    Miscellaneous_Technical,
    Control_Pictures,
    Optical_Character_Recognition,
    Enclosed_Alphanumerics,
    Box_Drawing,
    Block_Elements,
    Geometric_Shapes,
    Miscellaneous_Symbols,
    Dingbats,
    Miscellaneous_Mathematical_Symbols_A,
    Supplemental_Arrows_A,
    Braille_Patterns,
    Supplemental_Arrows_B,
    Miscellaneous_Mathematical_Symbols_B,
    Supplemental_Mathematical_Operators,
    Miscellaneous_Symbols_and_Arrows,
    Glagolitic,
    Latin_Extended_C,
    Coptic,
    Georgian_Supplement,
    Tifinagh,
    Ethiopic_Extended,
    Cyrillic_Extended_A,
    Supplemental_Punctuation,
    CJK_Radicals_Supplement,
    Kangxi_Radicals,
    Ideographic_Description_Characters,
    CJK_Symbols_and_Punctuation,
    Hiragana,
    Katakana,
    Bopomofo,
    Hangul_Compatibility_Jamo,
    Kanbun,
    Bopomofo_Extended,
    CJK_Strokes,
    Katakana_Phonetic_Extensions,
    Enclosed_CJK_Letters_and_Months,
    CJK_Compatibility,
    CJK_Unified_Ideographs_Extension_A,
    Yijing_Hexagram_Symbols,
    CJK_Unified_Ideographs,
    Yi_Syllables,
    Yi_Radicals,
    Lisu,
    Vai,
    Cyrillic_Extended_B,
    Bamum,
    Modifier_Tone_Letters,
    Latin_Extended_D,
    Syloti_Nagri,
    Common_Indic_Number_Forms,
    Phags_pa,
    Saurashtra,
    Devanagari_Extended,
    Kayah_Li,
    Rejang,
    Hangul_Jamo_Extended_A,
    Javanese,
    Myanmar_Extended_B,
    Cham,
    Myanmar_Extended_A,
    Tai_Viet,
    Meetei_Mayek_Extensions,
    Ethiopic_Extended_A,
    Latin_Extended_E,
    Cherokee_Supplement,
    Meetei_Mayek,
    Hangul_Syllables,
    Hangul_Jamo_Extended_B,
    High_Surrogates,
    High_Private_Use_Surrogates,
    Low_Surrogates,
    Private_Use_Area,
    CJK_Compatibility_Ideographs,
    Alphabetic_Presentation_Forms,
    Arabic_Presentation_Forms_A,
    Variation_Selectors,
    Vertical_Forms,
    Combining_Half_Marks,
    CJK_Compatibility_Forms,
    Small_Form_Variants,
    Arabic_Presentation_Forms_B,
    Halfwidth_and_Fullwidth_Forms,
    Specials,
    Linear_B_Syllabary,
    Linear_B_Ideograms,
    Aegean_Numbers,
    Ancient_Greek_Numbers,
    Ancient_Symbols,
    Phaistos_Disc,
    Lycian,
    Carian,
    Coptic_Epact_Numbers,
    Old_Italic,
    Gothic,
    Old_Permic,
    Ugaritic,
    Old_Persian,
    Deseret,
    Shavian,
    Osmanya,
    Osage,
    Elbasan,
    Caucasian_Albanian,
    Linear_A,
    Cypriot_Syllabary,
    Imperial_Aramaic,
    Palmyrene,
    Nabataean,
    Hatran,
    Phoenician,
    Lydian,
    Meroitic_Hieroglyphs,
    Meroitic_Cursive,
    Kharoshthi,
    Old_South_Arabian,
    Old_North_Arabian,
    Manichaean,
    Avestan,
    Inscriptional_Parthian,
    Inscriptional_Pahlavi,
    Psalter_Pahlavi,
    Old_Turkic,
    Old_Hungarian,
    Hanifi_Rohingya,
    Rumi_Numeral_Symbols,
    Yezidi,
    Old_Sogdian,
    Sogdian,
    Chorasmian,
    Elymaic,
    Brahmi,
    Kaithi,
    Sora_Sompeng,
    Chakma,
    Mahajani,
    Sharada,
    Sinhala_Archaic_Numbers,
    Khojki,
    Multani,
    Khudawadi,
    Grantha,
    Newa,
    Tirhuta,
    Siddham,
    Modi,
    Mongolian_Supplement,
    Takri,
    Ahom,
    Dogra,
    Warang_Citi,
    Dives_Akuru,
    Nandinagari,
    Zanabazar_Square,
    Soyombo,
    Pau_Cin_Hau,
    Bhaiksuki,
    Marchen,
    Masaram_Gondi,
    Gunjala_Gondi,
    Makasar,
    Lisu_Supplement,
    Tamil_Supplement,
    Cuneiform,
    Cuneiform_Numbers_and_Punctuation,
    Early_Dynastic_Cuneiform,
    Egyptian_Hieroglyphs,
    Egyptian_Hieroglyph_Format_Controls,
    Anatolian_Hieroglyphs,
    Bamum_Supplement,
    Mro,
    Bassa_Vah,
    Pahawh_Hmong,
    Medefaidrin,
    Miao,
    Ideographic_Symbols_and_Punctuation,
    Tangut,
    Tangut_Components,
    Khitan_Small_Script,
    Tangut_Supplement,
    Kana_Supplement,
    Kana_Extended_A,
    Small_Kana_Extension,
    Nushu,
    Duployan,
    Shorthand_Format_Controls,
    Byzantine_Musical_Symbols,
    Musical_Symbols,
    Ancient_Greek_Musical_Notation,
    Mayan_Numerals,
    Tai_Xuan_Jing_Symbols,
    Counting_Rod_Numerals,
    Mathematical_Alphanumeric_Symbols,
    Sutton_SignWriting,
    Glagolitic_Supplement,
    Nyiakeng_Puachue_Hmong,
    Wancho,
    Mende_Kikakui,
    Adlam,
    Indic_Siyaq_Numbers,
    Ottoman_Siyaq_Numbers,
    Arabic_Mathematical_Alphabetic_Symbols,
    Mahjong_Tiles,
    Domino_Tiles,
    Playing_Cards,
    Enclosed_Alphanumeric_Supplement,
    Enclosed_Ideographic_Supplement,
    Miscellaneous_Symbols_and_Pictographs,
    Emoticons,
    Ornamental_Dingbats,
    Transport_and_Map_Symbols,
    Alchemical_Symbols,
    Geometric_Shapes_Extended,
    Supplemental_Arrows_C,
    Supplemental_Symbols_and_Pictographs,
    Chess_Symbols,
    Symbols_and_Pictographs_Extended_A,
    Symbols_for_Legacy_Computing,
    CJK_Unified_Ideographs_Extension_B,
    CJK_Unified_Ideographs_Extension_C,
    CJK_Unified_Ideographs_Extension_D,
    CJK_Unified_Ideographs_Extension_E,
    CJK_Unified_Ideographs_Extension_F,
    CJK_Compatibility_Ideographs_Supplement,
    CJK_Unified_Ideographs_Extension_G,
    Tags,
    Variation_Selectors_Supplement,
    Supplementary_Private_Use_Area_A,
    Supplementary_Private_Use_Area_B,
};

constexpr uint32_t getFirstCodePoint(Block unicode_block) {
    switch(unicode_block) {
        case Block::Basic_Latin :
            return 0x0;
        case Block::Latin_1_Supplement :
            return 0x80;
        case Block::Latin_Extended_A :
            return 0x100;
        case Block::Latin_Extended_B :
            return 0x180;
        case Block::IPA_Extensions :
            return 0x250;
        case Block::Spacing_Modifier_Letters :
            return 0x2B0;
        case Block::Combining_Diacritical_Marks :
            return 0x300;
        case Block::Greek_and_Coptic :
            return 0x370;
        case Block::Cyrillic :
            return 0x400;
        case Block::Cyrillic_Supplement :
            return 0x500;
        case Block::Armenian :
            return 0x530;
        case Block::Hebrew :
            return 0x590;
        case Block::Arabic :
            return 0x600;
        case Block::Syriac :
            return 0x700;
        case Block::Arabic_Supplement :
            return 0x750;
        case Block::Thaana :
            return 0x780;
        case Block::NKo :
            return 0x7C0;
        case Block::Samaritan :
            return 0x800;
        case Block::Mandaic :
            return 0x840;
        case Block::Syriac_Supplement :
            return 0x860;
        case Block::Arabic_Extended_A :
            return 0x8A0;
        case Block::Devanagari :
            return 0x900;
        case Block::Bengali :
            return 0x980;
        case Block::Gurmukhi :
            return 0xA00;
        case Block::Gujarati :
            return 0xA80;
        case Block::Oriya :
            return 0xB00;
        case Block::Tamil :
            return 0xB80;
        case Block::Telugu :
            return 0xC00;
        case Block::Kannada :
            return 0xC80;
        case Block::Malayalam :
            return 0xD00;
        case Block::Sinhala :
            return 0xD80;
        case Block::Thai :
            return 0xE00;
        case Block::Lao :
            return 0xE80;
        case Block::Tibetan :
            return 0xF00;
        case Block::Myanmar :
            return 0x1000;
        case Block::Georgian :
            return 0x10A0;
        case Block::Hangul_Jamo :
            return 0x1100;
        case Block::Ethiopic :
            return 0x1200;
        case Block::Ethiopic_Supplement :
            return 0x1380;
        case Block::Cherokee :
            return 0x13A0;
        case Block::Unified_Canadian_Aboriginal_Syllabics :
            return 0x1400;
        case Block::Ogham :
            return 0x1680;
        case Block::Runic :
            return 0x16A0;
        case Block::Tagalog :
            return 0x1700;
        case Block::Hanunoo :
            return 0x1720;
        case Block::Buhid :
            return 0x1740;
        case Block::Tagbanwa :
            return 0x1760;
        case Block::Khmer :
            return 0x1780;
        case Block::Mongolian :
            return 0x1800;
        case Block::Unified_Canadian_Aboriginal_Syllabics_Extended :
            return 0x18B0;
        case Block::Limbu :
            return 0x1900;
        case Block::Tai_Le :
            return 0x1950;
        case Block::New_Tai_Lue :
            return 0x1980;
        case Block::Khmer_Symbols :
            return 0x19E0;
        case Block::Buginese :
            return 0x1A00;
        case Block::Tai_Tham :
            return 0x1A20;
        case Block::Combining_Diacritical_Marks_Extended :
            return 0x1AB0;
        case Block::Balinese :
            return 0x1B00;
        case Block::Sundanese :
            return 0x1B80;
        case Block::Batak :
            return 0x1BC0;
        case Block::Lepcha :
            return 0x1C00;
        case Block::Ol_Chiki :
            return 0x1C50;
        case Block::Cyrillic_Extended_C :
            return 0x1C80;
        case Block::Georgian_Extended :
            return 0x1C90;
        case Block::Sundanese_Supplement :
            return 0x1CC0;
        case Block::Vedic_Extensions :
            return 0x1CD0;
        case Block::Phonetic_Extensions :
            return 0x1D00;
        case Block::Phonetic_Extensions_Supplement :
            return 0x1D80;
        case Block::Combining_Diacritical_Marks_Supplement :
            return 0x1DC0;
        case Block::Latin_Extended_Additional :
            return 0x1E00;
        case Block::Greek_Extended :
            return 0x1F00;
        case Block::General_Punctuation :
            return 0x2000;
        case Block::Superscripts_and_Subscripts :
            return 0x2070;
        case Block::Currency_Symbols :
            return 0x20A0;
        case Block::Combining_Diacritical_Marks_for_Symbols :
            return 0x20D0;
        case Block::Letterlike_Symbols :
            return 0x2100;
        case Block::Number_Forms :
            return 0x2150;
        case Block::Arrows :
            return 0x2190;
        case Block::Mathematical_Operators :
            return 0x2200;
        case Block::Miscellaneous_Technical :
            return 0x2300;
        case Block::Control_Pictures :
            return 0x2400;
        case Block::Optical_Character_Recognition :
            return 0x2440;
        case Block::Enclosed_Alphanumerics :
            return 0x2460;
        case Block::Box_Drawing :
            return 0x2500;
        case Block::Block_Elements :
            return 0x2580;
        case Block::Geometric_Shapes :
            return 0x25A0;
        case Block::Miscellaneous_Symbols :
            return 0x2600;
        case Block::Dingbats :
            return 0x2700;
        case Block::Miscellaneous_Mathematical_Symbols_A :
            return 0x27C0;
        case Block::Supplemental_Arrows_A :
            return 0x27F0;
        case Block::Braille_Patterns :
            return 0x2800;
        case Block::Supplemental_Arrows_B :
            return 0x2900;
        case Block::Miscellaneous_Mathematical_Symbols_B :
            return 0x2980;
        case Block::Supplemental_Mathematical_Operators :
            return 0x2A00;
        case Block::Miscellaneous_Symbols_and_Arrows :
            return 0x2B00;
        case Block::Glagolitic :
            return 0x2C00;
        case Block::Latin_Extended_C :
            return 0x2C60;
        case Block::Coptic :
            return 0x2C80;
        case Block::Georgian_Supplement :
            return 0x2D00;
        case Block::Tifinagh :
            return 0x2D30;
        case Block::Ethiopic_Extended :
            return 0x2D80;
        case Block::Cyrillic_Extended_A :
            return 0x2DE0;
        case Block::Supplemental_Punctuation :
            return 0x2E00;
        case Block::CJK_Radicals_Supplement :
            return 0x2E80;
        case Block::Kangxi_Radicals :
            return 0x2F00;
        case Block::Ideographic_Description_Characters :
            return 0x2FF0;
        case Block::CJK_Symbols_and_Punctuation :
            return 0x3000;
        case Block::Hiragana :
            return 0x3040;
        case Block::Katakana :
            return 0x30A0;
        case Block::Bopomofo :
            return 0x3100;
        case Block::Hangul_Compatibility_Jamo :
            return 0x3130;
        case Block::Kanbun :
            return 0x3190;
        case Block::Bopomofo_Extended :
            return 0x31A0;
        case Block::CJK_Strokes :
            return 0x31C0;
        case Block::Katakana_Phonetic_Extensions :
            return 0x31F0;
        case Block::Enclosed_CJK_Letters_and_Months :
            return 0x3200;
        case Block::CJK_Compatibility :
            return 0x3300;
        case Block::CJK_Unified_Ideographs_Extension_A :
            return 0x3400;
        case Block::Yijing_Hexagram_Symbols :
            return 0x4DC0;
        case Block::CJK_Unified_Ideographs :
            return 0x4E00;
        case Block::Yi_Syllables :
            return 0xA000;
        case Block::Yi_Radicals :
            return 0xA490;
        case Block::Lisu :
            return 0xA4D0;
        case Block::Vai :
            return 0xA500;
        case Block::Cyrillic_Extended_B :
            return 0xA640;
        case Block::Bamum :
            return 0xA6A0;
        case Block::Modifier_Tone_Letters :
            return 0xA700;
        case Block::Latin_Extended_D :
            return 0xA720;
        case Block::Syloti_Nagri :
            return 0xA800;
        case Block::Common_Indic_Number_Forms :
            return 0xA830;
        case Block::Phags_pa :
            return 0xA840;
        case Block::Saurashtra :
            return 0xA880;
        case Block::Devanagari_Extended :
            return 0xA8E0;
        case Block::Kayah_Li :
            return 0xA900;
        case Block::Rejang :
            return 0xA930;
        case Block::Hangul_Jamo_Extended_A :
            return 0xA960;
        case Block::Javanese :
            return 0xA980;
        case Block::Myanmar_Extended_B :
            return 0xA9E0;
        case Block::Cham :
            return 0xAA00;
        case Block::Myanmar_Extended_A :
            return 0xAA60;
        case Block::Tai_Viet :
            return 0xAA80;
        case Block::Meetei_Mayek_Extensions :
            return 0xAAE0;
        case Block::Ethiopic_Extended_A :
            return 0xAB00;
        case Block::Latin_Extended_E :
            return 0xAB30;
        case Block::Cherokee_Supplement :
            return 0xAB70;
        case Block::Meetei_Mayek :
            return 0xABC0;
        case Block::Hangul_Syllables :
            return 0xAC00;
        case Block::Hangul_Jamo_Extended_B :
            return 0xD7B0;
        case Block::High_Surrogates :
            return 0xD800;
        case Block::High_Private_Use_Surrogates :
            return 0xDB80;
        case Block::Low_Surrogates :
            return 0xDC00;
        case Block::Private_Use_Area :
            return 0xE000;
        case Block::CJK_Compatibility_Ideographs :
            return 0xF900;
        case Block::Alphabetic_Presentation_Forms :
            return 0xFB00;
        case Block::Arabic_Presentation_Forms_A :
            return 0xFB50;
        case Block::Variation_Selectors :
            return 0xFE00;
        case Block::Vertical_Forms :
            return 0xFE10;
        case Block::Combining_Half_Marks :
            return 0xFE20;
        case Block::CJK_Compatibility_Forms :
            return 0xFE30;
        case Block::Small_Form_Variants :
            return 0xFE50;
        case Block::Arabic_Presentation_Forms_B :
            return 0xFE70;
        case Block::Halfwidth_and_Fullwidth_Forms :
            return 0xFF00;
        case Block::Specials :
            return 0xFFF0;
        case Block::Linear_B_Syllabary :
            return 0x10000;
        case Block::Linear_B_Ideograms :
            return 0x10080;
        case Block::Aegean_Numbers :
            return 0x10100;
        case Block::Ancient_Greek_Numbers :
            return 0x10140;
        case Block::Ancient_Symbols :
            return 0x10190;
        case Block::Phaistos_Disc :
            return 0x101D0;
        case Block::Lycian :
            return 0x10280;
        case Block::Carian :
            return 0x102A0;
        case Block::Coptic_Epact_Numbers :
            return 0x102E0;
        case Block::Old_Italic :
            return 0x10300;
        case Block::Gothic :
            return 0x10330;
        case Block::Old_Permic :
            return 0x10350;
        case Block::Ugaritic :
            return 0x10380;
        case Block::Old_Persian :
            return 0x103A0;
        case Block::Deseret :
            return 0x10400;
        case Block::Shavian :
            return 0x10450;
        case Block::Osmanya :
            return 0x10480;
        case Block::Osage :
            return 0x104B0;
        case Block::Elbasan :
            return 0x10500;
        case Block::Caucasian_Albanian :
            return 0x10530;
        case Block::Linear_A :
            return 0x10600;
        case Block::Cypriot_Syllabary :
            return 0x10800;
        case Block::Imperial_Aramaic :
            return 0x10840;
        case Block::Palmyrene :
            return 0x10860;
        case Block::Nabataean :
            return 0x10880;
        case Block::Hatran :
            return 0x108E0;
        case Block::Phoenician :
            return 0x10900;
        case Block::Lydian :
            return 0x10920;
        case Block::Meroitic_Hieroglyphs :
            return 0x10980;
        case Block::Meroitic_Cursive :
            return 0x109A0;
        case Block::Kharoshthi :
            return 0x10A00;
        case Block::Old_South_Arabian :
            return 0x10A60;
        case Block::Old_North_Arabian :
            return 0x10A80;
        case Block::Manichaean :
            return 0x10AC0;
        case Block::Avestan :
            return 0x10B00;
        case Block::Inscriptional_Parthian :
            return 0x10B40;
        case Block::Inscriptional_Pahlavi :
            return 0x10B60;
        case Block::Psalter_Pahlavi :
            return 0x10B80;
        case Block::Old_Turkic :
            return 0x10C00;
        case Block::Old_Hungarian :
            return 0x10C80;
        case Block::Hanifi_Rohingya :
            return 0x10D00;
        case Block::Rumi_Numeral_Symbols :
            return 0x10E60;
        case Block::Yezidi :
            return 0x10E80;
        case Block::Old_Sogdian :
            return 0x10F00;
        case Block::Sogdian :
            return 0x10F30;
        case Block::Chorasmian :
            return 0x10FB0;
        case Block::Elymaic :
            return 0x10FE0;
        case Block::Brahmi :
            return 0x11000;
        case Block::Kaithi :
            return 0x11080;
        case Block::Sora_Sompeng :
            return 0x110D0;
        case Block::Chakma :
            return 0x11100;
        case Block::Mahajani :
            return 0x11150;
        case Block::Sharada :
            return 0x11180;
        case Block::Sinhala_Archaic_Numbers :
            return 0x111E0;
        case Block::Khojki :
            return 0x11200;
        case Block::Multani :
            return 0x11280;
        case Block::Khudawadi :
            return 0x112B0;
        case Block::Grantha :
            return 0x11300;
        case Block::Newa :
            return 0x11400;
        case Block::Tirhuta :
            return 0x11480;
        case Block::Siddham :
            return 0x11580;
        case Block::Modi :
            return 0x11600;
        case Block::Mongolian_Supplement :
            return 0x11660;
        case Block::Takri :
            return 0x11680;
        case Block::Ahom :
            return 0x11700;
        case Block::Dogra :
            return 0x11800;
        case Block::Warang_Citi :
            return 0x118A0;
        case Block::Dives_Akuru :
            return 0x11900;
        case Block::Nandinagari :
            return 0x119A0;
        case Block::Zanabazar_Square :
            return 0x11A00;
        case Block::Soyombo :
            return 0x11A50;
        case Block::Pau_Cin_Hau :
            return 0x11AC0;
        case Block::Bhaiksuki :
            return 0x11C00;
        case Block::Marchen :
            return 0x11C70;
        case Block::Masaram_Gondi :
            return 0x11D00;
        case Block::Gunjala_Gondi :
            return 0x11D60;
        case Block::Makasar :
            return 0x11EE0;
        case Block::Lisu_Supplement :
            return 0x11FB0;
        case Block::Tamil_Supplement :
            return 0x11FC0;
        case Block::Cuneiform :
            return 0x12000;
        case Block::Cuneiform_Numbers_and_Punctuation :
            return 0x12400;
        case Block::Early_Dynastic_Cuneiform :
            return 0x12480;
        case Block::Egyptian_Hieroglyphs :
            return 0x13000;
        case Block::Egyptian_Hieroglyph_Format_Controls :
            return 0x13430;
        case Block::Anatolian_Hieroglyphs :
            return 0x14400;
        case Block::Bamum_Supplement :
            return 0x16800;
        case Block::Mro :
            return 0x16A40;
        case Block::Bassa_Vah :
            return 0x16AD0;
        case Block::Pahawh_Hmong :
            return 0x16B00;
        case Block::Medefaidrin :
            return 0x16E40;
        case Block::Miao :
            return 0x16F00;
        case Block::Ideographic_Symbols_and_Punctuation :
            return 0x16FE0;
        case Block::Tangut :
            return 0x17000;
        case Block::Tangut_Components :
            return 0x18800;
        case Block::Khitan_Small_Script :
            return 0x18B00;
        case Block::Tangut_Supplement :
            return 0x18D00;
        case Block::Kana_Supplement :
            return 0x1B000;
        case Block::Kana_Extended_A :
            return 0x1B100;
        case Block::Small_Kana_Extension :
            return 0x1B130;
        case Block::Nushu :
            return 0x1B170;
        case Block::Duployan :
            return 0x1BC00;
        case Block::Shorthand_Format_Controls :
            return 0x1BCA0;
        case Block::Byzantine_Musical_Symbols :
            return 0x1D000;
        case Block::Musical_Symbols :
            return 0x1D100;
        case Block::Ancient_Greek_Musical_Notation :
            return 0x1D200;
        case Block::Mayan_Numerals :
            return 0x1D2E0;
        case Block::Tai_Xuan_Jing_Symbols :
            return 0x1D300;
        case Block::Counting_Rod_Numerals :
            return 0x1D360;
        case Block::Mathematical_Alphanumeric_Symbols :
            return 0x1D400;
        case Block::Sutton_SignWriting :
            return 0x1D800;
        case Block::Glagolitic_Supplement :
            return 0x1E000;
        case Block::Nyiakeng_Puachue_Hmong :
            return 0x1E100;
        case Block::Wancho :
            return 0x1E2C0;
        case Block::Mende_Kikakui :
            return 0x1E800;
        case Block::Adlam :
            return 0x1E900;
        case Block::Indic_Siyaq_Numbers :
            return 0x1EC70;
        case Block::Ottoman_Siyaq_Numbers :
            return 0x1ED00;
        case Block::Arabic_Mathematical_Alphabetic_Symbols :
            return 0x1EE00;
        case Block::Mahjong_Tiles :
            return 0x1F000;
        case Block::Domino_Tiles :
            return 0x1F030;
        case Block::Playing_Cards :
            return 0x1F0A0;
        case Block::Enclosed_Alphanumeric_Supplement :
            return 0x1F100;
        case Block::Enclosed_Ideographic_Supplement :
            return 0x1F200;
        case Block::Miscellaneous_Symbols_and_Pictographs :
            return 0x1F300;
        case Block::Emoticons :
            return 0x1F600;
        case Block::Ornamental_Dingbats :
            return 0x1F650;
        case Block::Transport_and_Map_Symbols :
            return 0x1F680;
        case Block::Alchemical_Symbols :
            return 0x1F700;
        case Block::Geometric_Shapes_Extended :
            return 0x1F780;
        case Block::Supplemental_Arrows_C :
            return 0x1F800;
        case Block::Supplemental_Symbols_and_Pictographs :
            return 0x1F900;
        case Block::Chess_Symbols :
            return 0x1FA00;
        case Block::Symbols_and_Pictographs_Extended_A :
            return 0x1FA70;
        case Block::Symbols_for_Legacy_Computing :
            return 0x1FB00;
        case Block::CJK_Unified_Ideographs_Extension_B :
            return 0x20000;
        case Block::CJK_Unified_Ideographs_Extension_C :
            return 0x2A700;
        case Block::CJK_Unified_Ideographs_Extension_D :
            return 0x2B740;
        case Block::CJK_Unified_Ideographs_Extension_E :
            return 0x2B820;
        case Block::CJK_Unified_Ideographs_Extension_F :
            return 0x2CEB0;
        case Block::CJK_Compatibility_Ideographs_Supplement :
            return 0x2F800;
        case Block::CJK_Unified_Ideographs_Extension_G :
            return 0x30000;
        case Block::Tags :
            return 0xE0000;
        case Block::Variation_Selectors_Supplement :
            return 0xE0100;
        case Block::Supplementary_Private_Use_Area_A :
            return 0xF0000;
        case Block::Supplementary_Private_Use_Area_B :
            return 0x100000;
    }
}

constexpr uint32_t getLastCodePoint(Block unicode_block) {
    switch(unicode_block) {
        case Block::Basic_Latin :
            return 0x7F;
        case Block::Latin_1_Supplement :
            return 0xFF;
        case Block::Latin_Extended_A :
            return 0x17F;
        case Block::Latin_Extended_B :
            return 0x24F;
        case Block::IPA_Extensions :
            return 0x2AF;
        case Block::Spacing_Modifier_Letters :
            return 0x2FF;
        case Block::Combining_Diacritical_Marks :
            return 0x36F;
        case Block::Greek_and_Coptic :
            return 0x3FF;
        case Block::Cyrillic :
            return 0x4FF;
        case Block::Cyrillic_Supplement :
            return 0x52F;
        case Block::Armenian :
            return 0x58F;
        case Block::Hebrew :
            return 0x5FF;
        case Block::Arabic :
            return 0x6FF;
        case Block::Syriac :
            return 0x74F;
        case Block::Arabic_Supplement :
            return 0x77F;
        case Block::Thaana :
            return 0x7BF;
        case Block::NKo :
            return 0x7FF;
        case Block::Samaritan :
            return 0x83F;
        case Block::Mandaic :
            return 0x85F;
        case Block::Syriac_Supplement :
            return 0x86F;
        case Block::Arabic_Extended_A :
            return 0x8FF;
        case Block::Devanagari :
            return 0x97F;
        case Block::Bengali :
            return 0x9FF;
        case Block::Gurmukhi :
            return 0xA7F;
        case Block::Gujarati :
            return 0xAFF;
        case Block::Oriya :
            return 0xB7F;
        case Block::Tamil :
            return 0xBFF;
        case Block::Telugu :
            return 0xC7F;
        case Block::Kannada :
            return 0xCFF;
        case Block::Malayalam :
            return 0xD7F;
        case Block::Sinhala :
            return 0xDFF;
        case Block::Thai :
            return 0xE7F;
        case Block::Lao :
            return 0xEFF;
        case Block::Tibetan :
            return 0xFFF;
        case Block::Myanmar :
            return 0x109F;
        case Block::Georgian :
            return 0x10FF;
        case Block::Hangul_Jamo :
            return 0x11FF;
        case Block::Ethiopic :
            return 0x137F;
        case Block::Ethiopic_Supplement :
            return 0x139F;
        case Block::Cherokee :
            return 0x13FF;
        case Block::Unified_Canadian_Aboriginal_Syllabics :
            return 0x167F;
        case Block::Ogham :
            return 0x169F;
        case Block::Runic :
            return 0x16FF;
        case Block::Tagalog :
            return 0x171F;
        case Block::Hanunoo :
            return 0x173F;
        case Block::Buhid :
            return 0x175F;
        case Block::Tagbanwa :
            return 0x177F;
        case Block::Khmer :
            return 0x17FF;
        case Block::Mongolian :
            return 0x18AF;
        case Block::Unified_Canadian_Aboriginal_Syllabics_Extended :
            return 0x18FF;
        case Block::Limbu :
            return 0x194F;
        case Block::Tai_Le :
            return 0x197F;
        case Block::New_Tai_Lue :
            return 0x19DF;
        case Block::Khmer_Symbols :
            return 0x19FF;
        case Block::Buginese :
            return 0x1A1F;
        case Block::Tai_Tham :
            return 0x1AAF;
        case Block::Combining_Diacritical_Marks_Extended :
            return 0x1AFF;
        case Block::Balinese :
            return 0x1B7F;
        case Block::Sundanese :
            return 0x1BBF;
        case Block::Batak :
            return 0x1BFF;
        case Block::Lepcha :
            return 0x1C4F;
        case Block::Ol_Chiki :
            return 0x1C7F;
        case Block::Cyrillic_Extended_C :
            return 0x1C8F;
        case Block::Georgian_Extended :
            return 0x1CBF;
        case Block::Sundanese_Supplement :
            return 0x1CCF;
        case Block::Vedic_Extensions :
            return 0x1CFF;
        case Block::Phonetic_Extensions :
            return 0x1D7F;
        case Block::Phonetic_Extensions_Supplement :
            return 0x1DBF;
        case Block::Combining_Diacritical_Marks_Supplement :
            return 0x1DFF;
        case Block::Latin_Extended_Additional :
            return 0x1EFF;
        case Block::Greek_Extended :
            return 0x1FFF;
        case Block::General_Punctuation :
            return 0x206F;
        case Block::Superscripts_and_Subscripts :
            return 0x209F;
        case Block::Currency_Symbols :
            return 0x20CF;
        case Block::Combining_Diacritical_Marks_for_Symbols :
            return 0x20FF;
        case Block::Letterlike_Symbols :
            return 0x214F;
        case Block::Number_Forms :
            return 0x218F;
        case Block::Arrows :
            return 0x21FF;
        case Block::Mathematical_Operators :
            return 0x22FF;
        case Block::Miscellaneous_Technical :
            return 0x23FF;
        case Block::Control_Pictures :
            return 0x243F;
        case Block::Optical_Character_Recognition :
            return 0x245F;
        case Block::Enclosed_Alphanumerics :
            return 0x24FF;
        case Block::Box_Drawing :
            return 0x257F;
        case Block::Block_Elements :
            return 0x259F;
        case Block::Geometric_Shapes :
            return 0x25FF;
        case Block::Miscellaneous_Symbols :
            return 0x26FF;
        case Block::Dingbats :
            return 0x27BF;
        case Block::Miscellaneous_Mathematical_Symbols_A :
            return 0x27EF;
        case Block::Supplemental_Arrows_A :
            return 0x27FF;
        case Block::Braille_Patterns :
            return 0x28FF;
        case Block::Supplemental_Arrows_B :
            return 0x297F;
        case Block::Miscellaneous_Mathematical_Symbols_B :
            return 0x29FF;
        case Block::Supplemental_Mathematical_Operators :
            return 0x2AFF;
        case Block::Miscellaneous_Symbols_and_Arrows :
            return 0x2BFF;
        case Block::Glagolitic :
            return 0x2C5F;
        case Block::Latin_Extended_C :
            return 0x2C7F;
        case Block::Coptic :
            return 0x2CFF;
        case Block::Georgian_Supplement :
            return 0x2D2F;
        case Block::Tifinagh :
            return 0x2D7F;
        case Block::Ethiopic_Extended :
            return 0x2DDF;
        case Block::Cyrillic_Extended_A :
            return 0x2DFF;
        case Block::Supplemental_Punctuation :
            return 0x2E7F;
        case Block::CJK_Radicals_Supplement :
            return 0x2EFF;
        case Block::Kangxi_Radicals :
            return 0x2FDF;
        case Block::Ideographic_Description_Characters :
            return 0x2FFF;
        case Block::CJK_Symbols_and_Punctuation :
            return 0x303F;
        case Block::Hiragana :
            return 0x309F;
        case Block::Katakana :
            return 0x30FF;
        case Block::Bopomofo :
            return 0x312F;
        case Block::Hangul_Compatibility_Jamo :
            return 0x318F;
        case Block::Kanbun :
            return 0x319F;
        case Block::Bopomofo_Extended :
            return 0x31BF;
        case Block::CJK_Strokes :
            return 0x31EF;
        case Block::Katakana_Phonetic_Extensions :
            return 0x31FF;
        case Block::Enclosed_CJK_Letters_and_Months :
            return 0x32FF;
        case Block::CJK_Compatibility :
            return 0x33FF;
        case Block::CJK_Unified_Ideographs_Extension_A :
            return 0x4DBF;
        case Block::Yijing_Hexagram_Symbols :
            return 0x4DFF;
        case Block::CJK_Unified_Ideographs :
            return 0x9FFF;
        case Block::Yi_Syllables :
            return 0xA48F;
        case Block::Yi_Radicals :
            return 0xA4CF;
        case Block::Lisu :
            return 0xA4FF;
        case Block::Vai :
            return 0xA63F;
        case Block::Cyrillic_Extended_B :
            return 0xA69F;
        case Block::Bamum :
            return 0xA6FF;
        case Block::Modifier_Tone_Letters :
            return 0xA71F;
        case Block::Latin_Extended_D :
            return 0xA7FF;
        case Block::Syloti_Nagri :
            return 0xA82F;
        case Block::Common_Indic_Number_Forms :
            return 0xA83F;
        case Block::Phags_pa :
            return 0xA87F;
        case Block::Saurashtra :
            return 0xA8DF;
        case Block::Devanagari_Extended :
            return 0xA8FF;
        case Block::Kayah_Li :
            return 0xA92F;
        case Block::Rejang :
            return 0xA95F;
        case Block::Hangul_Jamo_Extended_A :
            return 0xA97F;
        case Block::Javanese :
            return 0xA9DF;
        case Block::Myanmar_Extended_B :
            return 0xA9FF;
        case Block::Cham :
            return 0xAA5F;
        case Block::Myanmar_Extended_A :
            return 0xAA7F;
        case Block::Tai_Viet :
            return 0xAADF;
        case Block::Meetei_Mayek_Extensions :
            return 0xAAFF;
        case Block::Ethiopic_Extended_A :
            return 0xAB2F;
        case Block::Latin_Extended_E :
            return 0xAB6F;
        case Block::Cherokee_Supplement :
            return 0xABBF;
        case Block::Meetei_Mayek :
            return 0xABFF;
        case Block::Hangul_Syllables :
            return 0xD7AF;
        case Block::Hangul_Jamo_Extended_B :
            return 0xD7FF;
        case Block::High_Surrogates :
            return 0xDB7F;
        case Block::High_Private_Use_Surrogates :
            return 0xDBFF;
        case Block::Low_Surrogates :
            return 0xDFFF;
        case Block::Private_Use_Area :
            return 0xF8FF;
        case Block::CJK_Compatibility_Ideographs :
            return 0xFAFF;
        case Block::Alphabetic_Presentation_Forms :
            return 0xFB4F;
        case Block::Arabic_Presentation_Forms_A :
            return 0xFDFF;
        case Block::Variation_Selectors :
            return 0xFE0F;
        case Block::Vertical_Forms :
            return 0xFE1F;
        case Block::Combining_Half_Marks :
            return 0xFE2F;
        case Block::CJK_Compatibility_Forms :
            return 0xFE4F;
        case Block::Small_Form_Variants :
            return 0xFE6F;
        case Block::Arabic_Presentation_Forms_B :
            return 0xFEFF;
        case Block::Halfwidth_and_Fullwidth_Forms :
            return 0xFFEF;
        case Block::Specials :
            return 0xFFFF;
        case Block::Linear_B_Syllabary :
            return 0x1007F;
        case Block::Linear_B_Ideograms :
            return 0x100FF;
        case Block::Aegean_Numbers :
            return 0x1013F;
        case Block::Ancient_Greek_Numbers :
            return 0x1018F;
        case Block::Ancient_Symbols :
            return 0x101CF;
        case Block::Phaistos_Disc :
            return 0x101FF;
        case Block::Lycian :
            return 0x1029F;
        case Block::Carian :
            return 0x102DF;
        case Block::Coptic_Epact_Numbers :
            return 0x102FF;
        case Block::Old_Italic :
            return 0x1032F;
        case Block::Gothic :
            return 0x1034F;
        case Block::Old_Permic :
            return 0x1037F;
        case Block::Ugaritic :
            return 0x1039F;
        case Block::Old_Persian :
            return 0x103DF;
        case Block::Deseret :
            return 0x1044F;
        case Block::Shavian :
            return 0x1047F;
        case Block::Osmanya :
            return 0x104AF;
        case Block::Osage :
            return 0x104FF;
        case Block::Elbasan :
            return 0x1052F;
        case Block::Caucasian_Albanian :
            return 0x1056F;
        case Block::Linear_A :
            return 0x1077F;
        case Block::Cypriot_Syllabary :
            return 0x1083F;
        case Block::Imperial_Aramaic :
            return 0x1085F;
        case Block::Palmyrene :
            return 0x1087F;
        case Block::Nabataean :
            return 0x108AF;
        case Block::Hatran :
            return 0x108FF;
        case Block::Phoenician :
            return 0x1091F;
        case Block::Lydian :
            return 0x1093F;
        case Block::Meroitic_Hieroglyphs :
            return 0x1099F;
        case Block::Meroitic_Cursive :
            return 0x109FF;
        case Block::Kharoshthi :
            return 0x10A5F;
        case Block::Old_South_Arabian :
            return 0x10A7F;
        case Block::Old_North_Arabian :
            return 0x10A9F;
        case Block::Manichaean :
            return 0x10AFF;
        case Block::Avestan :
            return 0x10B3F;
        case Block::Inscriptional_Parthian :
            return 0x10B5F;
        case Block::Inscriptional_Pahlavi :
            return 0x10B7F;
        case Block::Psalter_Pahlavi :
            return 0x10BAF;
        case Block::Old_Turkic :
            return 0x10C4F;
        case Block::Old_Hungarian :
            return 0x10CFF;
        case Block::Hanifi_Rohingya :
            return 0x10D3F;
        case Block::Rumi_Numeral_Symbols :
            return 0x10E7F;
        case Block::Yezidi :
            return 0x10EBF;
        case Block::Old_Sogdian :
            return 0x10F2F;
        case Block::Sogdian :
            return 0x10F6F;
        case Block::Chorasmian :
            return 0x10FDF;
        case Block::Elymaic :
            return 0x10FFF;
        case Block::Brahmi :
            return 0x1107F;
        case Block::Kaithi :
            return 0x110CF;
        case Block::Sora_Sompeng :
            return 0x110FF;
        case Block::Chakma :
            return 0x1114F;
        case Block::Mahajani :
            return 0x1117F;
        case Block::Sharada :
            return 0x111DF;
        case Block::Sinhala_Archaic_Numbers :
            return 0x111FF;
        case Block::Khojki :
            return 0x1124F;
        case Block::Multani :
            return 0x112AF;
        case Block::Khudawadi :
            return 0x112FF;
        case Block::Grantha :
            return 0x1137F;
        case Block::Newa :
            return 0x1147F;
        case Block::Tirhuta :
            return 0x114DF;
        case Block::Siddham :
            return 0x115FF;
        case Block::Modi :
            return 0x1165F;
        case Block::Mongolian_Supplement :
            return 0x1167F;
        case Block::Takri :
            return 0x116CF;
        case Block::Ahom :
            return 0x1173F;
        case Block::Dogra :
            return 0x1184F;
        case Block::Warang_Citi :
            return 0x118FF;
        case Block::Dives_Akuru :
            return 0x1195F;
        case Block::Nandinagari :
            return 0x119FF;
        case Block::Zanabazar_Square :
            return 0x11A4F;
        case Block::Soyombo :
            return 0x11AAF;
        case Block::Pau_Cin_Hau :
            return 0x11AFF;
        case Block::Bhaiksuki :
            return 0x11C6F;
        case Block::Marchen :
            return 0x11CBF;
        case Block::Masaram_Gondi :
            return 0x11D5F;
        case Block::Gunjala_Gondi :
            return 0x11DAF;
        case Block::Makasar :
            return 0x11EFF;
        case Block::Lisu_Supplement :
            return 0x11FBF;
        case Block::Tamil_Supplement :
            return 0x11FFF;
        case Block::Cuneiform :
            return 0x123FF;
        case Block::Cuneiform_Numbers_and_Punctuation :
            return 0x1247F;
        case Block::Early_Dynastic_Cuneiform :
            return 0x1254F;
        case Block::Egyptian_Hieroglyphs :
            return 0x1342F;
        case Block::Egyptian_Hieroglyph_Format_Controls :
            return 0x1343F;
        case Block::Anatolian_Hieroglyphs :
            return 0x1467F;
        case Block::Bamum_Supplement :
            return 0x16A3F;
        case Block::Mro :
            return 0x16A6F;
        case Block::Bassa_Vah :
            return 0x16AFF;
        case Block::Pahawh_Hmong :
            return 0x16B8F;
        case Block::Medefaidrin :
            return 0x16E9F;
        case Block::Miao :
            return 0x16F9F;
        case Block::Ideographic_Symbols_and_Punctuation :
            return 0x16FFF;
        case Block::Tangut :
            return 0x187FF;
        case Block::Tangut_Components :
            return 0x18AFF;
        case Block::Khitan_Small_Script :
            return 0x18CFF;
        case Block::Tangut_Supplement :
            return 0x18D8F;
        case Block::Kana_Supplement :
            return 0x1B0FF;
        case Block::Kana_Extended_A :
            return 0x1B12F;
        case Block::Small_Kana_Extension :
            return 0x1B16F;
        case Block::Nushu :
            return 0x1B2FF;
        case Block::Duployan :
            return 0x1BC9F;
        case Block::Shorthand_Format_Controls :
            return 0x1BCAF;
        case Block::Byzantine_Musical_Symbols :
            return 0x1D0FF;
        case Block::Musical_Symbols :
            return 0x1D1FF;
        case Block::Ancient_Greek_Musical_Notation :
            return 0x1D24F;
        case Block::Mayan_Numerals :
            return 0x1D2FF;
        case Block::Tai_Xuan_Jing_Symbols :
            return 0x1D35F;
        case Block::Counting_Rod_Numerals :
            return 0x1D37F;
        case Block::Mathematical_Alphanumeric_Symbols :
            return 0x1D7FF;
        case Block::Sutton_SignWriting :
            return 0x1DAAF;
        case Block::Glagolitic_Supplement :
            return 0x1E02F;
        case Block::Nyiakeng_Puachue_Hmong :
            return 0x1E14F;
        case Block::Wancho :
            return 0x1E2FF;
        case Block::Mende_Kikakui :
            return 0x1E8DF;
        case Block::Adlam :
            return 0x1E95F;
        case Block::Indic_Siyaq_Numbers :
            return 0x1ECBF;
        case Block::Ottoman_Siyaq_Numbers :
            return 0x1ED4F;
        case Block::Arabic_Mathematical_Alphabetic_Symbols :
            return 0x1EEFF;
        case Block::Mahjong_Tiles :
            return 0x1F02F;
        case Block::Domino_Tiles :
            return 0x1F09F;
        case Block::Playing_Cards :
            return 0x1F0FF;
        case Block::Enclosed_Alphanumeric_Supplement :
            return 0x1F1FF;
        case Block::Enclosed_Ideographic_Supplement :
            return 0x1F2FF;
        case Block::Miscellaneous_Symbols_and_Pictographs :
            return 0x1F5FF;
        case Block::Emoticons :
            return 0x1F64F;
        case Block::Ornamental_Dingbats :
            return 0x1F67F;
        case Block::Transport_and_Map_Symbols :
            return 0x1F6FF;
        case Block::Alchemical_Symbols :
            return 0x1F77F;
        case Block::Geometric_Shapes_Extended :
            return 0x1F7FF;
        case Block::Supplemental_Arrows_C :
            return 0x1F8FF;
        case Block::Supplemental_Symbols_and_Pictographs :
            return 0x1F9FF;
        case Block::Chess_Symbols :
            return 0x1FA6F;
        case Block::Symbols_and_Pictographs_Extended_A :
            return 0x1FAFF;
        case Block::Symbols_for_Legacy_Computing :
            return 0x1FBFF;
        case Block::CJK_Unified_Ideographs_Extension_B :
            return 0x2A6DF;
        case Block::CJK_Unified_Ideographs_Extension_C :
            return 0x2B73F;
        case Block::CJK_Unified_Ideographs_Extension_D :
            return 0x2B81F;
        case Block::CJK_Unified_Ideographs_Extension_E :
            return 0x2CEAF;
        case Block::CJK_Unified_Ideographs_Extension_F :
            return 0x2EBEF;
        case Block::CJK_Compatibility_Ideographs_Supplement :
            return 0x2FA1F;
        case Block::CJK_Unified_Ideographs_Extension_G :
            return 0x3134F;
        case Block::Tags :
            return 0xE007F;
        case Block::Variation_Selectors_Supplement :
            return 0xE01EF;
        case Block::Supplementary_Private_Use_Area_A :
            return 0xFFFFF;
        case Block::Supplementary_Private_Use_Area_B :
            return 0x10FFFF;
    }
}

constexpr uint32_t getBlockSize(Block unicode_block) {
    return getLastCodePoint(unicode_block) - getFirstCodePoint(unicode_block);
}

};


#endif // UNICODE_BLOCKS_HPP